<?php
/**
 * @category    ONE
 * @package     ONE_RevSlider
 * @copyright   Copyright (C) 2008-2014 nouthemes.com. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      nouthemes.com
 * @email       support.nouthemes.com
 */
?>
<div style="text-align: right;margin-bottom: 10px">
    <?php echo $this->getChildHtml('reset')?>
    <?php echo $this->getChildHtml('save')?>
    <span style="display: none" id="cssSaving">
        <img style="vertical-align: middle" src="<?php echo $this->getSkinUrl()?>images/rule-ajax-loader.gif"/>
    </span>
</div>
<div>
    <textarea id="css_editor" style="width: 100%;padding: 0" rows="35"><?php echo $this->getCssContent()?></textarea>
</div>
<script type="text/javascript">
    cssEditor = CodeMirror.fromTextArea(document.getElementById('css_editor'));
</script>
