<?php
/**
 * @category    ONE
 * @package     ONE_Widget
 * @copyright   Copyright (C) 2008-2014 nouthemes.com. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      nouthemes.com
 * @email       support.nouthemes.com
 */
?>
<tr>
    <td class="label">
        <?php echo $this->getElement()->getLabel()?>
    </td>
    <td class="value">
        <input type="hidden" id="<?php echo $this->getElement()->getHtmlId()?>"/>
        <?php echo $this->getElement()->getData('after_element_html')?>
    </td>
</tr>
