<?php
/**
 * @category    ONE
 * @package     ONE_Widget
 * @copyright   Copyright (C) 2008-2014 nouthemes.com. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      nouthemes.com
 * @email       support.nouthemes.com
 */
?>
<?php
$theme = $this->helper('bakery');
$helpImg = $this->helper('bakery/image');
$imgWidth = $theme->getCfg('category/image_width') ? $theme->getCfg('category/image_width') : 295;
$imgHeight = $theme->getCfg('category/image_height') ? $theme->getCfg('category/image_height') : 295;
if($theme->getCfg('category/aspect_ratio')){
    $imgHeight = 0;
}
$cfaltimage = $theme->getCfg('category/alt_image');
$hoveraltClass = ($cfaltimage == 1) ? 'front-img' : '';
$_helper            = $this->helper('catalog/output');
/* @var $this ONE_Widget_Block_Widget_Collection */
$productCollection  = $this->getData('collection');
$count              = $productCollection ? $productCollection->count() : 0;
$carousel           = $this->getData('carousel');
$row                = $this->getData('row');
$column             = $carousel == 1 && $row == 1 ? $count : ($carousel == 1 && $row > 1 ? $row : $this->getData('column'));
/* @var $helper Mage_Catalog_Helper_Image */
$helper             = Mage::helper('catalog/image');
?>
<?php if (!$count): ?>
    <p class="note-msg">
        <?php echo $this->__('There are no products matching the selection.') ?>
    </p>
<?php else: ?>
    <?php $i=0; foreach ($productCollection as $_product): ?>
      
    <div class="category-products collection-position03">
        <ul class="products-grid <?php echo $carousel && $row == 1 ? ' owl-carousel' : '' ?>">
      
         <li class="item">
            <div class="item-inner">
                <div class="product-item">
                   
                    <div class="name-price">
                        <h3 class="product-name">
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                                <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </h3>
                        <div class="std"><?php $product_tmp = Mage::getModel('catalog/product')->load($_product->entity_id); 
                            echo $product_tmp->description; ?>
                        </div>
                               <?php echo nl2br($this->htmlEscape($_product->getDescription())) ?>     
                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                        
                        <div class="one-actions1 clearfix">
                            <?php echo $this->getPriceHtml($_product, true) ?>
                            <div class="addtocart">

                                <?php if($_product->isSaleable()): ?>
                                    <?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) || $oType == true ) { ?>
                                        <button type="button" title="<?php echo $this->__('Order Now') ?>" data-placement="top" class="button btn-cart one-tooltip <?php if($oType == true) echo 'option-file';?>" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
										   <span>
										      <span><?php echo $this->__('Order Now ') ?><i class="fa fa-long-arrow-right"></i></span>
										   </span>
                                        </button>
                                    <?php } else { ?>
                                        <?php if (Mage::getStoreConfig('ajaxcart/ajaxcart_config/enable_ajaxcart')) : ?>
                                            <a style="display: none;" href='<?php echo $this->getUrl('ajaxcart/index/options',array('product_id'=>$_product->getId()));?>' class='options-cart' data-id='options-cart-<?php echo $_product->getId()?>'><?php echo $this->__('Option cart')?></a>
                                        <?php endif; ?>
                                        <button type="button" title="<?php echo $this->__('Order Now') ?>" data-placement="top" class="button btn-cart show-options one-tooltip" data-id="<?php echo $_product->getId(); ?>"
                                            <?php if (!Mage::getStoreConfig('ajaxcart/ajaxcart_config/enable_ajaxcart')) { ?>
                                                onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"
                                            <?php }?>><span> <span><?php echo $this->__('Order Now ') ?><i class="fa fa-long-arrow-right"></i></span></span></button>
                                    <?php }  ?>
                                <?php else: ?>
                                    <p class="availability out-of-stock pull-left" title="<?php echo $this->__('Out of stock') ?>">
                                        <span class="out"><?php echo $this->__('Out of stock') ?></span>
                                    </p>
                                <?php endif; ?>
                         
                            </div>

                        </div>
                    </div>
                    <div class="content products-list">
                        <div class="product-hover">
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                                <?php //echo $this->helper('bakery')->getLabel($_product);  ?>
                                <span class="front margin-image">
                                    <img class="img-responsive <?php echo $hoveraltClass;?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image') ?>" alt="" />
                                </span>
                               
                            </a>
                        </div>

                    </div>
                </div>
            </div>
        </li>
        
    </ul>

</div>
      
    <?php endforeach ?>
<?php endif ?>
