<?php
/**
 * @category    ONE
 * @package     ONE_Widget
 * @copyright   Copyright (C) 2008-2014 nouthemes.com. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      nouthemes.com
 * @email       support.nouthemes.com
 */
?>
<?php
$theme = $this->helper('bakery');
$helpImg = $this->helper('bakery/image');
$imgWidth = $theme->getCfg('category/image_width') ? $theme->getCfg('category/image_width') : 295;
$imgHeight = $theme->getCfg('category/image_height') ? $theme->getCfg('category/image_height') : 295;
if($theme->getCfg('category/aspect_ratio')){
    $imgHeight = 0;
}
$cfaltimage = $theme->getCfg('category/alt_image');
$hoveraltClass = ($cfaltimage == 1) ? 'front-img' : '';
$_helper            = $this->helper('catalog/output');
/* @var $this ONE_Widget_Block_Widget_Collection */
$productCollection  = $this->getData('collection');
$count              = $productCollection ? $productCollection->count() : 0;
$carousel           = $this->getData('carousel');
$row                = $this->getData('row');
$column             = $carousel == 1 && $row == 1 ? $count : ($carousel == 1 && $row > 1 ? $row : $this->getData('column'));
/* @var $helper Mage_Catalog_Helper_Image */
$helper             = Mage::helper('catalog/image');
?>
<?php if (!$count): ?>
    <p class="note-msg">
        <?php echo $this->__('There are no products matching the selection.') ?>
    </p>
<?php else: ?>
    <?php $i=0; foreach ($productCollection as $_product): ?>
        <?php /* @var $product Mage_Catalog_Model_Product */ ?>
        <?php if ($carousel == 1 && $row > 1 && $i == 0): ?>
            <div class="owl-carousel">
        <?php endif ?>
        <?php if ($i % $column == 0 || ($row > 1 && $i % $row == 0)): ?>
            <ul class="products-grid <?php echo $carousel && $row == 1 ? ' owl-carousel' : '' ?>">
        <?php endif ?>
        <?php $i++ ?>
        <li class="item">
            <div class="item-inner">
                <?php $i++ ?>
                <div class="product-item">
                    <div class="content products-list">
                        <div class="product-hover">
                            <a class="options-cart" href="<?php echo $this->getUrl('ajaxcart/index/options/product_id/' . $_product->getId()); ?>" id='options-cart-<?php echo $_product->getId()?>' style='display:none'><?php //echo $this->__('Quickview') ?></a>

                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                                <?php echo $this->helper('bakery')->getLabel($_product);  ?>
                                <div class="front margin-image">
                                    <img class="img-responsive lazy <?php echo $hoveraltClass;?>" data-src="<?php echo $helpImg->getImg($_product, $imgWidth, $imgHeight, 'small_image'); ?>" src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                                </div>
                                <div class="product-img-additional back margin-image">
                                    <?php if ($theme->getCfg('category/alt_image')): ?>
                                        <?php echo $theme->getAltImgHtml($_product, $imgWidth, $imgHeight); ?>
                                    <?php endif; ?>
                                </div>
                            </a>
                        </div>
                        <!--<div class="one-actions clearfix">

                            <div class="addtocart">
                                <div class="main-quickview hidden-xs">
                                    <button type="button" rel="tooltip"  data-placement="right" title="<?php echo $this->__('Quickview') ?>" class="button show-options" data-id="<?php echo $_product->getId(); ?>"><span><span><i class="fa fa-search"></i>&nbsp;&nbsp;<?php //echo $this->__('Quickview') ?></span></span></button>
                                </div>
                                <?php if($_product->isSaleable()): ?>
                                    <?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) || $oType == true ) { ?>
                                        <button type="button" title="<?php echo $this->__('Purchase') ?>" rel="tooltip" data-placement="right" class="button btn-cart <?php if($oType == true) echo 'option-file';?>" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
										   <span>
										      <span><i class="fa fa-shopping-cart"></i><?php echo $this->__('Purchase') ?></span>
										   </span>
                                        </button>
                                    <?php } else { ?>
                                        <?php if (Mage::getStoreConfig('ajaxcart/ajaxcart_config/enable_ajaxcart')) : ?>
                                            <a style="display: none;" href='<?php echo $this->getUrl('ajaxcart/index/options',array('product_id'=>$_product->getId()));?>' class='options-cart' id='options-cart-<?php echo $_product->getId()?>'><?php echo $this->__('Option cart')?></a>
                                        <?php endif; ?>
                                        <button type="button" title="<?php echo $this->__('Purchase') ?>" rel="tooltip" data-placement="right" class="button btn-cart show-options" data-id="<?php echo $_product->getId(); ?>"
                                            <?php if (!Mage::getStoreConfig('ajaxcart/ajaxcart_config/enable_ajaxcart')) { ?>
                                                onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"
                                            <?php }?>><span><span><i class="fa fa-shopping-cart"></i><?php echo $this->__('Purchase') ?></span></span></button>
                                    <?php }  ?>
                                <?php else: ?>
                                    <p class="availability out-of-stock pull-left" title="<?php echo $this->__('Out of stock') ?>">
                                        <span class="out"><?php echo $this->__('Out of stock') ?></span>
                                    </p>
                                <?php endif; ?>
                                <div class="confix-produclist">
                                    <div class="add-to-links">
                                        <div class="wishlist">
                                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                                <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" data-id="<?php echo $_product->getId(); ?>" title="<?php echo $this->__('Wishlist') ?>" rel="tooltip" data-placement="right" class="link-wishlist">
                                                    <i class="fa fa fa-heart-o"></i><?php //echo $this->__('Add to Wishlist') ?>
                                                </a>
                                            <?php endif; ?>
                                        </div>
                                        <div class="compare">
                                            <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                                <a href="<?php echo $_compareUrl ?>" data-id="<?php echo $_product->getId(); ?>" title="<?php echo $this->__('Compare') ?>" rel="tooltip" data-placement="right" class="link-compare">
                                                    <i class="fa fa-expand"></i><?php //echo $this->__('Add to Compare') ?>
                                                </a>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>-->
                    <div class="top-actions-inner">
                        <h3 class="product-name">
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                                <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </h3>
                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                        <?php echo $this->getPriceHtml($_product, true) ?>

                    </div>
                </div>
            </div>
        </li>
        <?php if ($i == $count || $i % $column == 0 || ($row > 1 && $i % $row == 0)): ?>
            </ul>
        <?php endif ?>
        <?php if ($carousel == 1 && $row > 1 && $i == $count): ?>
            </div>
        <?php endif ?>
    <?php endforeach ?>
<?php endif ?>
