<?php
/**
 * @category    ONE
 * @package     ONE_Widget
 * @copyright   Copyright (C) 2008-2014 nouthemes.com. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      nouthemes.com
 * @email       support.nouthemes.com
 */
?>
<?php
$_id                = $this->getConfig('id');
$_title             = $this->getConfig('widget_title');
$t                  = microtime();
?>

    <div class="<?php echo $this->getConfig('classes') ?>" id="<?php echo $_id ?>">
      
		<div class="block">
				<div class="block-title">
				        <?php if ($_title): ?>
							<strong><span><?php echo $_title ?></span></strong>
						<?php endif ?> 
				</div>
		</div>
		<?php echo $this->renderCollection('collection', $this->getData('mode'), 'one/widget/collection_positionright_detail.phtml') ?>
    </div>
    <script type="text/javascript" src="<?php echo Mage::getBaseUrl('js') ?>bakery/frontend.js"></script>
    <script type="text/javascript">
        new ONE.Widget('<?php echo $_id ?>', {
            animation: <?php echo $this->getConfig('animation') ?>,
            parallax: <?php echo $this->getConfig('parallax') ?>,
            carousel: <?php echo $this->getConfig('carousel') ?>
        });
    </script>

<?php //Mage::log(microtime() - $t) ?>
