<?php
/**
 * @category    ONE
 * @package     ONE_Widget
 * @copyright   Copyright (C) 2008-2014 nouthemes.com. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      nouthemes.com
 * @email       support.nouthemes.com
 */
?>
<?php
/* @var $this ONE_Widget_Block_Widget */
$id         = 'tabs';
$title      = $this->getConfig('widget_title');
$tabs       = $this->getTabs();
$template   = 'one/widget/collection_position03.phtml';
$t          = microtime();

?>
<div class="<?php echo $this->getConfig('classes') ?>" id="<?php echo $id ?>">
    <div class="tabs-collection">
            <div class="main-heading">
                <div class="heading-wrapper-title">
                        <?php if ($title): ?>
                            <h3><span><?php echo $title ?></span></h3>
                        <?php endif ?>
                </div>
            </div>
           
    </div>
    <div class="tab-product">
         <ul class="widget-tabs nav nav-tabs">
                    <?php foreach ($tabs as $index => $tab): ?>
                        <li class="<?php echo $index==0 ? 'active' : '' ?>">
                            <a href="#<?php echo $id . '-' . $tab['id'] ?>"
                                data-value="<?php echo $tab['value'] ?>"
                                data-type="<?php echo $tab['type'] ?>"
                                data-limit="<?php echo $this->getLimit() ?>"
                                data-column="<?php echo $this->getConfig('column') ?>"
                                data-row="<?php echo $this->getConfig('row') ?>"
                                data-cid="<?php echo $this->getData('category_ids') ?>"
                                data-template="<?php echo $template ?>"
                                data-carousel="<?php echo $this->getConfig('scroll') ?>">
                                <?php //echo $tab['label'] ?>
                                
                                <?php $values = $tab['value'];?>
                                <img src="<?php echo Mage::getModel('catalog/category')->load($values)->getImageUrl();?>" alt="" />

                                <?php //echo $tab['id'] ?>
                                <?php //echo $tab['value'] ?>
                            </a>
                        </li>
                    <?php endforeach ?>
                </ul>
        <div class="tab-content">
            <?php foreach ($tabs as $index => $tab): ?>
                <div id="<?php echo $id . '-' . $tab['id'] ?>" class="tab-pane<?php echo $index==0 ? ' active' : '' ?>">
                    <?php if ($index > 0): ?>
                        </div>
                        <?php continue ?>
                    <?php endif ?>
                    <?php echo $this->renderCollection($tab['type'], $tab['value'], $template) ?>
                </div>
            <?php endforeach ?>
        </div>
    </div>
    <script type="text/javascript" src="<?php echo Mage::getBaseUrl('js') ?>bakery/frontend.js"></script>
    <script type="text/javascript">
        new ONE.Widget('<?php echo $id ?>', {
            collectionUrl: '<?php echo $this->getUrl('onewidget/collection/get') ?>',
            collectionCallback: function(){}
        });
    </script>
</div>
<?php //Mage::log(microtime() - $t) ?>
