<?php
/**
 * @category    ONE
 * @package     ONE_Filter
 * @copyright   Copyright (C) 2008-2013 nouthemes.com. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      nouthemes.com
 * @email       support.nouthemes.com
 */
?>
<?php
    $bar = Mage::helper('onefilter')->getConfig('onefilter/general/bar');
    $barColor = '#'.Mage::helper('onefilter')->getConfig('onefilter/general/bar_color');
?>
<div id="<?php echo $this->getHash()?>" class="price-slider">
    <div id="<?php echo $this->getHash('-min')?>" class="price-slider-handle min"></div>
    <div id="<?php echo $this->getHash('-max')?>" class="price-slider-handle max"></div>
    <div id="<?php echo $this->getHash('-span')?>" class="price-slider-span"></div>
</div>
<div class="layer-price">
    <?php echo $this->getCurrencySymbol()?><span id="layer-price-min"></span>&nbsp;&nbsp;-&nbsp;&nbsp;<?php echo $this->getCurrencySymbol()?><span id="layer-price-max"></span>
</div>
<style type="text/css">
    .price-slider{
        height: 8px;
        width: 86%;
        background: #f3f3f3;
        position: relative;
        margin: 11px auto;
        -webkit-touch-callout: none;
        -webkit-user-select: none;
        -khtml-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
    }
    .price-slider .price-slider-handle{
		border: 2px solid #684f40;
        border-radius: 50%;
        height: 20px;
        position: absolute;
        top: -7px;
        width: 20px;
    }
   .price-slider .price-slider-handle:before{content: "";background: #684f40;
        border-radius: 50%;
        content: "";
        height: 10px;
        left: 3px;
        position: absolute;
        top: 3px;
        width: 10px;
    }
    .layer-price{
        text-align: center;
    }
</style>
<script type="text/javascript">
    window.oneFilter.initPriceFilter(<?php echo $this->getConfig()?>);
</script>