<?php

/**

 *

 * ------------------------------------------------------------------------------

 * @category     ONE

 * @package      ONE_Themes

 * ------------------------------------------------------------------------------

 * @copyright    Copyright (C) 2008-2013 nouthemes.com. All Rights Reserved.

 * @license      GNU General Public License version 2 or later;

 * @author       nouthemes.com

 * @email        support.nouthemes.com

 * ------------------------------------------------------------------------------

 *

 */

?>

<!-- navigation BOF -->

<div class="block block-nav">

    <div class="block-title">

        <strong><span><?php echo $this->__('Categories'); ?></span></strong>

    </div>

    <div class="block-content">

        <ul id="categories_nav" class="nav-accordion nav-categories">

            <?php echo $this->renderCategoriesMenuHtml(TRUE, TRUE, 0, 'level-top'); ?>
            <?php                 
            if(Mage::getStoreConfig('bakery/menu/enable_custom')){                    
                $getidentifier = Mage::getStoreConfig('bakery/menu/static_identifier');                    
                $arrayidentifier = explode(";", $getidentifier);                    
                foreach($arrayidentifier as $mcustom){                        
                    $static_block = explode(':', $mcustom);                        
                    $custom_menu = Mage::getModel('cms/block')->load($static_block[0]);                        
                    if($static_block[1]) $class = 'menu-item-'.$static_block[1];                        

                    if($custom_menu->getIsActive()) {                            
                        echo '                            
                        <li class="level0 level-top parent custom-block '.$class.'">                                
                            <a href="#" class="level-top">                                    
                                <span>'.$custom_menu->getTitle().'</span>                                
                            </a>                                
                            <div class="sub-wrapper">'.$this->getLayout()->createBlock('cms/block')->setBlockId($static_block[0])->toHtml().'</div>                            
                        </li>';                        
                    }                    
                }                     
        $urlkey = Mage::getStoreConfig('bakery/menu/url_key');                    
        $arrayUrlKey = explode(";", $urlkey);                    
        foreach($arrayUrlKey as $url){                        
            $condition = explode(':', $url);                        
            $page = Mage::getModel('cms/page')->load($condition[0], 'identifier');                        
            if(isset($condition[1])) $class = 'menu-item-'.$condition[1];                        
            if($page->getIsActive()) {                    
                ?>                         
                <li class="level0 level-top parent custom-block <?php if($routeName == 'cms' && $identifier == $page->getIdentifier()) {echo " active";}?> <?php echo $class;?>">                            

                    <a href="<?php echo Mage::helper('cms/page')->getPageUrl($condition[0]);?>" class="level-top">                                
                        <span><?php echo $page->getTitle();?></span>                            
                    </a>                         
                </li>                     
                <?php                         
            }                    
        }                
    }            
    ?>            
        <?php if($top_menu = 1){?>                
        <li class="level0 level-top">                    
            <a href="<?php echo $this->getUrl('blog');?>" class="level-top">                        
                <?php echo "blog";?>                    
            </a>                
        </li>             
        <?php } ?>            
        <li class="level0 level-top">                
            <a href="<?php echo $this->getUrl('contacts');?>" class="level-top">                    
                <?php echo "contact";?>                
            </a>            
        </li>  
        

        </ul>
        <script type="text/javascript">
            $one(document).ready(function() {
                $one("#categories_nav").oneAccordionMenu({
                    accordion:true,
                    speed: 400,
                    closedSign: 'slideUp',
                    openedSign: 'slideDown',
                    mouseType: 0,
                    easing: 'easeInOutQuad'
                });
            });
        </script>

    

    </div>

</div>

<!-- navigation EOF -->