<?php

/**

 *

 * ------------------------------------------------------------------------------

 * @category     ONE

 * @package      ONE_Themes

 * ------------------------------------------------------------------------------

 * @copyright    Copyright (C) 2008-2013 nouthemes.com. All Rights Reserved.

 * @license      GNU General Public License version 2 or later;

 * @author       nouthemes.com

 * @email        support.nouthemes.com

 * ------------------------------------------------------------------------------

 *

 */

?>

<!-- navigation BOF -->

<?php 

$theme = $this->helper('bakery');

$megaeffect = Mage::getStoreConfig('bakery/menu/effect');

$sticky_logo = $theme->getCfg('header/sticky_logo');

$_menu = $this->renderCategoriesMenuHtml(FALSE, FALSE, 0, 'level-top', 'sub-wrapper' );

$routeName = Mage::app()->getRequest()->getRouteName();

$identifier = Mage::getSingleton('cms/page')->getIdentifier(); 
$top_menu = Mage::getStoreConfig('blog/slide/topmenu');
 

?> 

<!--<div class="navbar visible-xs">

    <div class="navbar navbar-inverse">

        <div class="container">

            <div class="navbar-header">

                <div class="navbar-toggle" type="button" data-toggle="collapse">

                    <span class="sr-only"><?php //echo $this->__('Navigation');?></span>

                    <span class="icon-bar"></span>

                    <span class="icon-bar"></span>

                    <span class="icon-bar"></span>

                </div>

            </div>

        </div>

    </div>

</div>-->

<?php if($_menu): ?>

<div class="one-navigation hidden-xs">

    <?php  

        $logoSrc = $this->getSkinUrl($sticky_logo);

        $logoArc = Mage::getStoreConfig('design/header/logo_alt');

	?>

	<div class="logo-sticky" style="display: none;">

        <a href="<?php echo $this->getUrl('') ?>">

            <img class="img-sticky" src="<?php echo $logoSrc; ?>" alt="<?php echo $logoArc; ?>" />

        </a>

    </div>

	<div class="one-main-menu">

		<ul id="onenav" class="megamenu">

			<?php if(Mage::getStoreConfig('bakery/menu/home')){?>

			<li class="level0 home level-top <?php if($routeName == 'cms' && $identifier == 'home') {echo " active";}?> m-dropdown parent">

				<a href="<?php echo $this->getBaseUrl(); ?>" class="level-top"><span><?php echo $this->__('Home'); ?></span></a>

			</li> 

			<?php }?>

			<?php

			echo $_menu;

			if(Mage::getStoreConfig('bakery/menu/enable_custom')){

				$getidentifier = Mage::getStoreConfig('bakery/menu/static_identifier');

				$arrayidentifier = explode(";", $getidentifier);

				foreach($arrayidentifier as $mcustom){

                    $static_block = explode(':', $mcustom);

					$custom_menu = Mage::getModel('cms/block')->load($static_block[0]);

                    if($static_block[1]) $class = 'menu-item-'.$static_block[1];

					if($custom_menu->getIsActive()) {

						echo '

						<li class="level0 level-top parent custom-block '.$class.'">

							<a href="#" class="level-top">

								<span>'.$custom_menu->getTitle().'</span>

							</a>

							<div class="sub-wrapper">'.$this->getLayout()->createBlock('cms/block')->setBlockId($static_block[0])->toHtml().'</div>

						</li>';

					}

				} 

				$urlkey = Mage::getStoreConfig('bakery/menu/url_key');

				$arrayUrlKey = explode(";", $urlkey);

				foreach($arrayUrlKey as $url){

                    $condition = explode(':', $url);

					$page = Mage::getModel('cms/page')->load($condition[0], 'identifier');

                    if(isset($condition[1])) $class = 'menu-item-'.$condition[1];

					if($page->getIsActive()) {

				?> 

					<li class="level0 level-top parent custom-block <?php if($routeName == 'cms' && $identifier == $page->getIdentifier()) {echo " active";}?> <?php echo $class;?>">

						<a href="<?php echo Mage::helper('cms/page')->getPageUrl($condition[0]);?>" class="level-top">

							<span><?php echo $page->getTitle();?></span>

						</a> 

					</li> 

				<?php 

					}

				}

			}

			?>
			<?php if($top_menu = 1){?>
				<li class="level0 level-top">
					<a href="<?php echo $this->getUrl('blog');?>" class="level-top">
						<?php echo "blog";?>
					</a>
				</li> 
			<?php } ?>
			<li class="level0 level-top">
				<a href="<?php echo $this->getUrl('contacts');?>" class="level-top">
					<?php echo "contact";?>
				</a>
			</li> 
		</ul>

	</div>

</div>

<script type="text/javascript">

    $one(function(){

        $one(".megamenu").megamenu({

            'animation':'<?php echo $megaeffect;?>',

            'mm_timeout': 150

	    });

    });

</script>

<?php endif ?>

<!-- navigation EOF -->