<?php
/**
 *
 * ------------------------------------------------------------------------------
 * @category     ONE
 * @package      ONE_Themes
 * ------------------------------------------------------------------------------
 * @copyright    Copyright (C) 2008-2013 nouthemes.com. All Rights Reserved.
 * @license      GNU General Public License version 2 or later;
 * @author       nouthemes.com
 * @email        support.nouthemes.com
 * ------------------------------------------------------------------------------
 *
 */
?>
<!-- navigation BOF -->
<?php 
$megaeffect = Mage::getStoreConfig('bakery/menu/menuleft_effect');
$_menu = $this->renderCategoriesMenuHtml(FALSE, FALSE, 0, 'level-top', 'sub-wrapper' );
$routeName = Mage::app()->getRequest()->getRouteName();
$identifier = Mage::getSingleton('cms/page')->getIdentifier(); 
 
?>
<?php if($_menu): ?>
<div class="one-navigation-vertical block hidden-xs">
    <div class="block-title">
        <strong>
            <span><?php echo $this->__('All Category'); ?></span>
            <span class="fa fa-angle-down"></span>
        </strong>
    </div>
	<div class="one-main-menu-vertical" style="display:none">
		<ul class="megamenu-vertical">
			<!--<?php if(Mage::getStoreConfig('bakery/menu/home')){?>
			<li class="level0 home level-top<?php if($routeName == 'cms' && $identifier == 'home') {echo " active";}?> m-dropdown parent">
				<a href="<?php echo $this->getBaseUrl(); ?>" class="level-top"><span><?php echo $this->__('Home'); ?></span></a>
			</li> 
			<?php }?>-->
			<?php
			echo $_menu;
			?>
		</ul>
	</div>
</div>
<script type="text/javascript">
    $one(function(){
        $one(".megamenu-vertical").vmegamenu({
            'animation':'<?php echo $megaeffect;?>',
            'direction': 'vertical',
            'mm_timeout': 50
	    });
    });
</script>
<?php endif ?>
<!-- navigation EOF -->