<?php
$enabled_slide = Mage::getStoreConfig('blog/slide/enabled');
$width_slide = Mage::getStoreConfig('blog/slide/width');
$numbercolumn_slide = Mage::getStoreConfig('blog/slide/numbercolumn');
$numberrow = Mage::getStoreConfig('blog/slide/numberrow');
$speed_slide = Mage::getStoreConfig('blog/slide/speed');
$auto_slide = Mage::getStoreConfig('blog/slide/auto');
$show_image = Mage::getStoreConfig('blog/slide/showimage');
$image_width = Mage::getStoreConfig('blog/slide/widthimage');
$image_height = Mage::getStoreConfig('blog/slide/heightimage');
$show_title = Mage::getStoreConfig('blog/slide/showtitle');
$show_author = Mage::getStoreConfig('blog/slide/showauthor');
$show_time = Mage::getStoreConfig('blog/slide/showtime');
$show_shortcontent = Mage::getStoreConfig('blog/slide/showshortcontent');
$show_readmore = Mage::getStoreConfig('blog/slide/showreadmore');
if($enabled_slide){
?>
<?php echo '<script type="text/javascript" src="'. $this->getBaseUrl().'js/bakery/owl.carousel.js"></script>'?>

<script>
	/*$jq(document).ready(function(){
		$jq('.menu-recent .bxslider').bxSlider({
			minSlides: <?php if($numbercolumn_slide) echo $numbercolumn_slide; else echo '1'; ?>,
			maxSlides: <?php if($numbercolumn_slide) echo $numbercolumn_slide; else echo '1'; ?>,
			slideWidth: <?php if($width_slide) echo $width_slide; else  echo '900'; ?>,
			auto: <?php if($auto_slide) echo 'true'; else echo 'false'; ?>,
			autoControls: false,
			pager: false,
			mode: 'horizontal',
			speed: <?php if($speed_slide) echo $speed_slide; else echo '100'; ?>,
			prevText: '<i class="fa fa-arrow-left"></i>',
			nextText: '<i class="fa fa-arrow-right"></i>',
			pause: 4000,
			easing: 'jswing',
			autoHover: true
		});
	});*/

	jQuery(document).ready(function($) {

      jQuery(".bxslider").owlCarousel({
        items : <?php if($numbercolumn_slide) echo $numbercolumn_slide; else echo '1'; ?>,
        lazyLoad : true,
        navigation : true
      });

    });
</script>
<?php if ($posts = $this->getRecent()):  $i = 1;?>
	<div class="menu-recent">
		<div class="container">
			<div class="title">
<!--				<h3 class="title2"><?php // echo $this->__('Blog posts') ?></h3>-->
                            <h3 class="title2">EVENEMENTS 2015</h3>
				<div class="bg-title"></div>
			</div>
		<div class="bxslider">
		<?php if($numberrow > 1){ ?>
			<?php foreach ($posts as $post): ?>
				<?php if($i % $numberrow == 1) echo '<ul><li>'; ?>
					<?php if($show_image) echo '<img width="'.$image_width.'px" height="'.$image_height.'px" src="'.Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA). $post->getThumbnailimage().'" alt=""/>'; ?>
					<?php if($show_title): ?> <a href="<?php echo $post->getAddress(); ?>" ><?php echo '<h3 class="title">'.$post->getTitle().'</h3>' ?></a> <?php endif; ?>
					<?php $s = $post->getCreatedTime(); $date = strtotime($s); ?>
					<?php if($show_author) echo '<p>By '.$post->getUser(); if($show_author && $show_time) echo ' - '; if($show_time) echo date("d M Y", $date).'</p>'; ?>
					<?php if($show_shortcontent) echo $this->getContentBlogSidebar($post->getShortContent(),100);?>
					<?php if($show_readmore): ?> <p><a href="<?php echo $post->getAddress(); ?>">Read more >></a></p> <?php endif; ?>
				<?php if($i % $numberrow == 0)echo '</li></ul>'; $i++; ?>
			<?php endforeach; ?>
			<?php if($i % $numberrow != 1)echo '</li></ul>'; ?>
		<?php } else{ ?>
			<?php foreach ($posts as $post): ?>
				<ul><li>
					<div class="blog-item">
						<a href="<?php echo $post->getAddress(); ?>" >
							<?php if($show_image) echo '<img  width="'.$image_width.'" height="'.$image_height.'"  src="'.Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA). $post->getThumbnailimage().'" alt=""/>'; ?>
						</a>
					<?php if($show_title): ?>
					
					<h3 class="title-blog-item"><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle() ?></a></h3> <?php endif; ?>
					<?php $s = $post->getCreatedTime(); $date = strtotime($s); ?>
					<?php if($show_shortcontent) echo $this->getContentBlogSidebar($post->getShortContent(),100);?>
					<div class="blog-bottom">
						<?php if($show_author) echo '<p class="author"> By '.$post->getUser().'</p>'; ?>
						<?php if($show_author) echo '<p class="date">'; if($show_time) echo date("d M, Y", $date).'</p>'; ?>
						<?php if($show_readmore): ?> <p><a class="read-more" href="<?php echo $post->getAddress(); ?>">Read more</a></p> <?php endif; ?>
					</div>
			
					</div>
				</li></ul>
			<?php endforeach; ?>
		<?php } ?>
		</div>
		</div>
	</div>
<?php endif;
}else {

?>
<?php if ($posts = $this->getRecent()):  $i = 1;?>
	<div class="menu-recent">
		<div class="container">
			<div class="title">
				<p class="title1"><?php echo $this->__('Weekly edit') ?></p>
				<h3 class="title2"><?php echo $this->__('our of blog') ?></h3>
				<div class="bg-title"></div>
			</div>
		<ul class="bxslider">
	
			<?php foreach ($posts as $post): ?>
				<li>
					<div class="blog-item">
					<?php if($show_image) echo '<img  width="'.$image_width.'px" height="'.$image_height.'px"  src="'.Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA). $post->getThumbnailimage().'" />'; ?>
					<?php if($show_title): ?>
					<?php if($show_author) echo '<p class="date">'; if($show_time) echo date("d M, Y", $date).'</p>'; ?>
					<h3 class="title-blog-item"><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle() ?></a></h3> <?php endif; ?>
					<?php $s = $post->getCreatedTime(); $date = strtotime($s); ?>
					<?php if($show_shortcontent) echo $this->getContentBlogSidebar($post->getShortContent(),100);?>
					<div class="blog-bottom">
						<?php if($show_author) echo '<p class="author"> By '.$post->getUser().'</p>'; ?>
						<?php if($show_author) echo '<p class="date">'; if($show_time) echo date("d M, Y", $date).'</p>'; ?>
						<?php if($show_readmore): ?> <p><a class="read-more" href="<?php echo $post->getAddress(); ?>">Read more</a></p> <?php endif; ?>
					</div>
					
					</div>
				</li>
			<?php endforeach; ?>

		</ul>
		</div>
	</div>
<?php endif;


}
?>
