<?php
$theme = $this->helper('bakery');
$equalHeight = $theme->getCfg('category_grid/equal_height');
$displayAddtocart = $theme->getCfg('category_grid/display_addtocart');
$displayAddtolink = $theme->getCfg('category_grid/display_addtolinks');
$compareHeader = $theme->getCfg('header/compare');
?>
<script type="text/javascript">
    <?php if ($equalHeight): ?>
    function setGridItemsEqualHeight($)
    {
        var winWidth = $(window).width();
        var SPACING = 0;
        if (winWidth >= 480)
        {
            $('.show-grid').removeClass("auto-height");
            var gridItemMaxHeight = 0;
            $('.show-grid > .item').each(function() {
                $(this).css("height", "auto");
                <?php if ($displayAddtocart == 2 || $displayAddtolink == 2): ?>
                var actionsHeight = $(this).find('.actions').height();
                $(this).css("padding-bottom", (actionsHeight + SPACING) + "px"); //Set new padding
                <?php endif; ?>
                gridItemMaxHeight = Math.max(gridItemMaxHeight, $(this).height());
            });
            $('.show-grid > .item').css("height", gridItemMaxHeight + "px");
        }
        else
        {
            $('.show-grid').addClass("auto-height");
            $('.show-grid > .item').css("height", "auto");
            $('.show-grid > .item').css("padding-bottom", "20px");
        }
    }
    <?php endif; ?>
    function setGridItem($){
        var winWidth = $(window).width();
        var col = <?php echo $theme->getCfg('category_grid/column_count');?>;
        if(winWidth > 768){
            newcol = col;
        }
        if(winWidth < 768 && winWidth >=640){
            newcol = <?php echo $theme->getCfg('category_grid/column_count_768');?>;
        }
        if(winWidth >=480 && winWidth <640){
            newcol = <?php echo $theme->getCfg('category_grid/column_count_640');?>;
        }
        if(winWidth < 480){
            newcol = <?php echo $theme->getCfg('category_grid/column_count_480');?>;
        }
        $i = 0;
        $('.show-grid > .item').each(function() {
            $i++;
            $(this).removeClass('first');
            $(this).removeClass('last');
            if(($i-1)%newcol==0){
                $(this).addClass('first');
            }else if($i%newcol==0){
                $(this).addClass('last');
            }
        });
    }
    $one(function($) {
        var winWidth = $(window).width();
        var winHeight = $(window).height();
        var windowResize_t;
        $(window).resize(function() {
            var winNewWidth = $(window).width();
            var winNewHeight = $(window).height();
            if (winWidth != winNewWidth || winHeight != winNewHeight)
            {
                clearTimeout(windowResize_t);
                windowResize_t = setTimeout(function() {
                    $(document).trigger("themeResize");
                    <?php if ($equalHeight): ?>
                    setGridItemsEqualHeight($);
                    <?php endif; ?>
                    setGridItem($);
                }, 200);
            }
            winWidth = winNewWidth;
            winHeight = winNewHeight;
        });
        <?php if($compareHeader):?>
        $('.one-maincompare').hover(
            function () {
                $(this).addClass('compare-active').find('.oneajaxcompare').stop().delay(200).slideDown();
            },
            function () {
                $(this).removeClass('compare-active').find('.oneajaxcompare').stop().delay(200).slideUp();
            }
        );
        <?php endif; ?> 
          $('.all-category').hover(
            function () {
                $(this).addClass('setting-bi-active').find('.one-main-menu-vertical').stop().delay(200).slideDown();
            },
            function () {
                $(this).removeClass('setting-bi-active').find('.one-main-menu-vertical').stop().delay(200).slideUp();
            }
        );
        $("#select-language").selectbox();
        $("#select-currency").selectbox();
        //lazyload
        $("img.lazy").lazy({
            effect : "fadeIn",
            effectTime: 800,
            threshold: 50, 
            afterLoad: function(element) {
                <?php if ($equalHeight): ?>
                setGridItemsEqualHeight($);
                <?php endif; ?>
            }
        });

        //Back to top
        $(window).scroll(function () {
            if ($(this).scrollTop() > 100) {
                $('#back-top').fadeIn();
            } else {
                $('#back-top').fadeOut();
            }
        });
        $('#back-top a').click(function () {
            $('body,html').animate({
                scrollTop: 0
            }, 800);
            return false;
        });
        //Cart header
        $('.header-container .one-maincart .summary').click(function(){
                $('body').find('.header-cart').addClass('cart-active').stop().delay(200).slideDown();
            });
        $('.header-container .one-maincart .empty').click(function(){
                $('body').find('.header-cart').addClass('cart-active').stop().delay(200).slideDown();
            });
    
        $('.header-cart .icon-close').click(function(){
                $('body').find('.header-cart').removeClass('cart-active').stop().delay(200).slideUp();
            }); 
           
       



    jQuery('#zo2-top-wrap .icon-search').click(function(){
        jQuery('.search .search-form').fadeIn('300');
        jQuery('#zo2-top-wrap .search .search-form .inputbox').focus().css("color","#000");
    });
        jQuery('#zo2-top-wrap .search-close').click(function(){
        jQuery('.search .search-form').fadeOut('300');
    });


        $('.header-content-right .seach').hover(
            function () {
                $(this).addClass('active').find('.form').stop().delay(200).slideDown();
            },
            function () {
                $(this).removeClass('active').find('.form').stop().delay(200).slideUp();
            }
        );
        //Quickview
        $('.product-quickview').live('click', function() {
            $.colorbox({
                iframe: true,
                href:this.href,
                opacity:    0.5,
                speed:      300,
                current:    '{current} / {total}',
                close:      "close",
                innerWidth:'780px',
                innerHeight:'650px',
                onOpen: function(){
                    $('#cboxLoadingGraphic').addClass('box-loading');
                },
                onComplete: function(){
                    setTimeout(function(){
                        $('#cboxLoadingGraphic').removeClass('box-loading');
                    },1300);
                }
            });
        });

        $('.show-quickview').live('click', function(e){
            if($('.btn-cart-mobile').length == 0){
                $(this).next().trigger('click');
            }else{
                return window.location.href=$(this).attr('data-submit');
            }
        });
    });
    $one(window).load(function(){
        <?php if ($equalHeight): ?>
        setGridItemsEqualHeight($one);
        <?php endif; ?>
        setGridItem($one);
    });
    // JavaScript Document
    $one(window).load(function(){
        $one(".one-tooltip").tooltip();
        var selectToggle = '<i class="fa fa-sort-down"></i>';
        var flextPrev = '<i class="fa fa-angle-left"></i>',
            iconMenu = '<i class="fa fa-angle-down"></i>',
            revoNext = '<i class="fa fa-arrow-right"></i>',
            revoPrev = '<i class="fa fa-arrow-left"></i>',
            revoBullet = '<i class="fa fa-circle"></i>',
            flextNext = '<i class="fa fa-angle-right"></i>';

        $one(".flex-direction-nav a").empty();
        $one(".flex-direction-nav a.flex-prev").append(flextPrev);
        $one(".flex-direction-nav a.flex-next").append(flextNext);
        //$one(".level0.sub-wrapper").prev('.level-top').append(iconMenu);
        $one(".tp-leftarrow.default").append(revoPrev);
        $one(".tp-rightarrow.default").append(revoNext);
        $one(".tp-bullets .bullet").append(revoBullet);
        $one(".sbToggle").append(selectToggle);
    });
    //function iconFontAwesome() {
        //add font icon awesome

      //  $one(".links li a").append("<i></i>");
       // $one(".links li.first i").addClass("fa fa-user");
       // $one(".links li a.top-link-wishlist i").addClass("fa fa-heart-o");
      //  $one(".links li a.top-link-checkout i").addClass("fa fa-check");
      //  $one(".links li.last i").addClass("fa fa-unlock-alt");


    //}
    
    $one(".accordion-footer").addClass("accordion-show");
        $one(".accordion-footer").click(function(){
            if($one(this).parent().next().is(":visible")){
                $one(this).addClass("accordion-show");
            }else{
                $one(this).removeClass("accordion-show");
            }
            $one(this).parent().next().toggle(400);
        });
</script>