<?php
/**
 * @category    ONE
 * @package     ONE_RevSlider
 * @copyright   Copyright (C) 2008-2014 nouthemes.com. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      nouthemes.com
 * @email       support.nouthemes.com
 */
?>
<tr>
    <td class="label"></td>
    <td class="value" style="">
        <?php echo $this->getChildHtml('edit')?>
        <?php echo $this->getChildHtml('new')?>
    </td>
</tr>
