<?php
/**
 * @category    ONE
 * @package     ONE_RevSlider
 * @copyright   Copyright (C) 2008-2014 nouthemes.com. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      nouthemes.com
 * @email       support.nouthemes.com
 */
?>
<?php
$element = $this->getElement();
$id = $element->getHtmlId();
?>
<tr>
    <td colspan="2">
        <div style="width: 100%">
            <textarea style="" id="<?php echo $id ?>"></textarea>
        </div>
    </td>
</tr>
